# Basic
title: 蘑小De菇
subtitle: 个人技术博客
welcome_message: 记录个人对技术的理解和开发过程中遇到的问题，欢迎了解更多。
description:  hi，我是蘑小De菇，一名前端开发者。
creator: 蘑小De菇

url: https://moxiaodegu.github.io/

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: 访问博客

tag_button:
    title: Tag
    description: 文章分类
    url: 'https://moxiaodegu.github.io/tag/'  

# Navigation buttons in the front page.
nav:
    - {title: GitHub, description: 个人代码, url: 'https://github.com/moxiaodegu'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: 
    # duoshuo: 
    
# Social
social:
    github: moxiaodegu
    mail: moxiaodegu@163.com

# Google Analytics
ga:
     id: UA-142143336-1
     host: auto
